version: '3'

volumes:
  news_parser:

services:

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: api
    command: flask run
    container_name: api
    env_file:
      - .env
    restart: always
    tty: True
    working_dir: /api
    ports: 
        - "5000:5000"
    networks:
      - parser_network

  pg_db:
    image: postgres
    restart: unless-stopped
    container_name: parsingmarkets
    env_file:
      - .env
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - parser_network

  parser:
    build:
      context: .
      dockerfile: parser/Dockerfile
    image: parser
    container_name: parser
    env_file:
      - .env
    restart: always
    tty: True
    working_dir: /parser
    networks:
      - parser_network

networks:
  parser_network:
    driver: bridge
